workspaceApiUrl: https://api.watsonwork.ibm.com

# Your values here
appId: c44cf95b-e923-40ef-a3ed-38fb06a71914
appSecret: biszu4e217rr44ryst3mt8kcdtzh19ma
webhookSecret: a5tzr8z8x2ppho3e492hcb1a6z4m0may

#Server config, specifies port and uses self-signed keystore
server:
    applicationConnectors:
        - type: http
          port: 8080
        - type: https
          port: 8443
          keyStorePath: skeleton.keystore
          keyStorePassword: skeleton
          validateCerts: false
# trustStorePath is only necessary on macos, replace JAVA_HOME with your own java home
#          trustStorePath: JAVA_HOME/jre/lib/security/cacerts